export const SCHEDULE_LIST = [
  {
    start: '8:00am',
    end: '8:55am',
    type: 'event',
    title: 'Registration',
    speakers: [],
  },
  {
    start: '9:00am',
    end: '9:30am',
    type: 'keynote',
    title: 'The State of npm',
    speakers: ['Issac Schlueter'],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'Get Excited and Inspired',
    speakers: [],
  },
  {
    start: '9:35am',
    end: '10:00am',
    type: 'talk',
    title: '',
    speakers: ['Wolf Rentzsch'],
  },
  {
    start: '9:00am',
    end: '9:30am',
    type: 'keynote',
    title: 'The Ins-and-Outs of Publishing a Module to npm',
    speakers: ['Steve Kinney'],
  },
  {
    start: '10:35am',
    end: '10:50am',
    type: 'event',
    title: 'Break',
    speakers: [],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'npm in Strange Places',
    speakers: [],
  },
  {
    start: '10:55am',
    end: '11:20am',
    type: 'talk',
    title: 'npm, nodebots, and What We Bring to the Node.JS Community',
    speakers: ['Kassandra Perch'],
  },
  {
    start: '11:25am',
    end: '11:50am',
    type: 'talk',
    title: 'Node.js and Microsoft: A love story about developer tools',
    speakers: ['Sara Itani'],
  },
  {
    start: '11:55am',
    end: '12:20pm',
    type: 'panel',
    title: 'Package Managers: Before and After npm',
    speakers: [
      'Andre Arko',
      'Steve Klabnik',
      'Samuel Giddins',
      'Ashley Williams',
    ],
  },
  {
    start: '12:25pm',
    end: '1:25pm',
    type: 'event',
    title: 'Lunch',
    speakers: [],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'Practical How-Tos',
    speakers: [],
  },
  {
    start: '1:30pm',
    end: '1:55pm',
    type: 'talk',
    title: 'Testing for Accessibility with aXe',
    speakers: ['Marcy Sutton'],
  },
  {
    start: '2:00pm',
    end: '2:25pm',
    type: 'talk',
    title: 'Ember.js, DevOps, and You: Lessons Learned From Building an Ember Addon',
    speakers: ['Iheanyi Ekechukwu'],
  },
  {
    start: '2:30pm',
    end: '2:55pm',
    type: 'talk',
    title: 'A tale of two front-end development environments: or how bend npm3 to your will',
    speakers: ['Kate Hudson'],
  },
  {
    start: '3:00pm',
    end: '3:15pm',
    type: 'event',
    title: 'Break',
    speakers: [],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'npm in Production',
    speakers: [],
  },
  {
    start: '3:20pm',
    end: '3:30pm',
    type: 'lightning',
    title: 'Automating SemVer for Fun and Profit: Tools and Practices to Make Releasing Easier',
    speakers: ['Andrew Goode'],
  },
  {
    start: '3:35pm',
    end: '3:45pm',
    type: 'lightning',
    title: '',
    speakers: [],
  },
  {
    start: '3:20pm',
    end: '3:30pm',
    type: 'lightning',
    title: 'Twirling toward freedom: The rewards (and challenges) of open source support',
    speakers: ['Steph Snopek', 'Kiera Manion-Fischer'],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'The Modular Lifestyle',
    speakers: [],
  },
  {
    start: '4:05pm',
    end: '4:30pm',
    type: 'talk',
    title: 'Greenkeeper – managing dependencies with confidence',
    speakers: ['Stephan Bönnemann'],
  },
  {
    start: '4:35pm',
    end: '5:00pm',
    type: 'talk',
    title: 'You don\'t suck at communication: an empathetic communication primer',
    speakers: ['Sharon Steed'],
  },
  {
    start: '5:05pm',
    end: '5:30pm',
    type: 'event',
    title: 'Break',
    speakers: [],
  },
  {
    start: '',
    end: '',
    type: 'section',
    title: 'npm Open Source',
    speakers: [],
  },
  {
    start: '5:35pm',
    end: '5:45pm',
    type: 'lightning',
    title: 'Asynchronous wombats: developing OSS globally',
    speakers: ['Daijiro Wachi'],
  },
  {
    start: '5:50pm',
    end: '6:00pm',
    type: 'lightning',
    title: 'Educating Your Community to grow from Safe to Inclusive',
    speakers: ['February Keeney'],
  },
  {
    start: '6:05pm',
    end: '6:15pm',
    type: 'lightning',
    title: 'State of the CLI: npm@3, stability, feature work, and beyond~',
    speakers: ['Kat Marchán'],
  },
  {
    start: '6:20pm',
    end: '6:50pm',
    type: 'keynote',
    title: 'Registry Design Patterns',
    speakers: ['CJ Silverio'],
  },
  {
    start: '7:00pm',
    end: '8:30pm',
    type: 'event',
    title: 'Dinner break',
    speakers: [],
  },
  {
    start: '8:30pm',
    end: '',
    type: 'event',
    title: 'Dance.JS',
    speakers: ['Ben Coe (organizer)', ' CJ Silverio (DJ)'],
  },
];
