export const SPEAKER_LIST = [
  { name: 'Iheanyi Ekechukwu',
    image: require('./assets/iheanyi-ekechukwu.jpg'),
    talkTitle: 'Ember.js, DevOps, and You: Lessons Learned From Building an Ember Addon',
    talkType: 'talk', bio: '',
  },
  { name: 'February Keeney',
    image: require('./assets/february-keeney.jpg'),
    talkTitle: 'Educating Your Community to grow from Safe to Inclusive',
    talkType: 'lightning', bio: '',
  },
  { name: 'Sharon Steed',
    image: require('./assets/sharon-steed.jpg'),
    talkTitle: 'You don\'t suck at communication: an empathetic communication primer',
    talkType: 'talk', bio: '',
  },
  { name: 'Steve Kinney',
    image: require('./assets/steve-kinney.jpg'),
    talkTitle: 'The Ins-and-Outs of Publishing a Module to npm',
    talkType: 'talk', bio: '',
  },
  { name: 'Marcy Sutton',
    image: require('./assets/marcy-sutton.jpg'),
    talkTitle: 'Testing for Accessibility with aXe',
    talkType: 'talk', bio: '',
  },
  { name: 'Sara Itani',
    image: require('./assets/sara-itani.jpg'),
    talkTitle: 'Node.js and Microsoft: A love story about developer tools',
    talkType: 'talk', bio: '',
  },
  { name: 'Andre Arko',
    image: require('./assets/andre-arko.jpg'),
    talkTitle: 'Package Managers: Before and After npm',
    talkType: 'panel', bio: '',
  },
  { name: 'Steve Klabnik',
    image: require('./assets/steve-klabnik.jpg'),
    talkTitle: 'Package Managers: Before and After npm',
    talkType: 'panel', bio: '',
  },
  { name: 'Cj Silverio',
    image: require('./assets/cj-silverio.jpg'),
    talkTitle: 'Registry Design Patterns',
    talkType: 'keynote', bio: '',
  },
  { name: 'Daijiro Wachi',
    image: require('./assets/daijiro-wachi.jpg'),
    talkTitle: 'Asynchronous wombats: developing OSS globally',
    talkType: 'lightning', bio: '',
  },
  { name: 'Ashley Williams',
    image: require('./assets/ashley-williams.jpg'),
    talkTitle: 'Package Managers: Before and After npm',
    talkType: 'panel', bio: '',
  },
  { name: 'Wolf Rentzsch',
    image: require('./assets/wolf-rentzsch.jpg'),
    talkTitle: '',
    talkType: 'talk', bio: '',
  },
  { name: 'Kat Marchan',
    image: require('./assets/kat-marchan.jpg'),
    talkTitle: 'TALKState of the CLI: npm@3, stability, feature work, and beyond~',
    talkType: 'lightning', bio: '',
  },
  { name: 'Kate Hudson',
    image: require('./assets/kate-hudson.png'),
    talkTitle: 'A tale of two front-end development environments: or how bend npm3 to your will',
    talkType: 'talk', bio: '',
  },
  { name: 'Steph Snopek',
    image: require('./assets/steph-snopek.jpg'),
    talkTitle: 'Twirling toward freedom: The rewards (and challenges) of open source support',
    talkType: 'lightning', bio: '',
  },
  { name: 'Kiera Manion-Fischer',
    image: require('./assets/kiera-manion.jpg'),
    talkTitle: 'Twirling toward freedom: The rewards (and challenges) of open source support',
    talkType: 'lightning', bio: '',
  },
  { name: 'Kassandra Perch',
    image: require('./assets/kassandra-perch.jpg'),
    talkTitle: 'npm, nodebots, and What We Bring to the Node.JS Community',
    talkType: 'talk', bio: '',
  },
  { name: 'Samuel Giddins',
    image: require('./assets/samuel-giddins.jpg'),
    talkTitle: 'Package Managers: Before and After npm',
    talkType: 'panel', bio: '',
  },
  { name: 'Stephan Bonnemann',
    image: require('./assets/stephan-bonnemann.jpg'),
    talkTitle: 'Greenkeeper – managing dependencies with confidence',
    talkType: 'talk', bio: '',
  },
  { name: 'Isaac Schlueter',
    image: require('./assets/isaac-schlueter.png'),
    talkTitle: 'The State of npm',
    talkType: 'keynote', bio: '',
  },
  { name: 'Andrew Goode',
    image: require('./assets/andrew-goode.jpg'),
    talkTitle: 'Automating SemVer for Fun and Profit: Tools and Practices to Make Releasing Easier',
    talkType: 'lightning', bio: '',
  },
  { name: 'Raquel Velez',
    image: require('./assets/raquel-velez.jpg'),
    talkTitle: '',
    talkType: '', bio: '',
  },
  { name: 'Not Found',
    image: require('./assets/not-found.png'),
    talkTitle: '',
    talkType: '', bio: '',
  },
];
